-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 10:43:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_ALMCNAMIENTO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_ALMCNAMIENTO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_ALMCNAMIENTO` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_ALMCNAMIENTO` ;

-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`comentario` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`comentario` (
  `idcomentario` INT NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `fecha_c` DATETIME NOT NULL,
  `comentario_idcomentario` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `comentario_idcomentario`),
  INDEX `fk_comentario_comentario1_idx` (`comentario_idcomentario` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_comentario1`
    FOREIGN KEY (`comentario_idcomentario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`comentario` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`historial_contraseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`historial_contraseña` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`historial_contraseña` (
  `idhistorial` INT NOT NULL,
  `estado` ENUM("activa", "inactiva") NOT NULL,
  `contraseña_act` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhistorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correoe` VARCHAR(45) NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `pregunta_s` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `respuesta_s` VARCHAR(45) NOT NULL,
  `comentario_idcomentario` INT NOT NULL,
  `historial_contraseña_idhistorial` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `comentario_idcomentario`, `historial_contraseña_idhistorial`),
  UNIQUE INDEX `credenciales_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Usuario_comentario1_idx` (`comentario_idcomentario` ASC) VISIBLE,
  INDEX `fk_Usuario_historial_contraseña1_idx` (`historial_contraseña_idhistorial` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_comentario1`
    FOREIGN KEY (`comentario_idcomentario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`comentario` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_historial_contraseña1`
    FOREIGN KEY (`historial_contraseña_idhistorial`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`historial_contraseña` (`idhistorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`categoria` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nombre_c` VARCHAR(100) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idcategoria`, `categoria_idcategoria`),
  INDEX `fk_categoria_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`documento` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`documento` (
  `iddocumento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `URL` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `visibilidad` ENUM("piblico", "privado") NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `comentario_idcomentario` INT NOT NULL,
  `comentario_comentario_idcomentario` INT NOT NULL,
  PRIMARY KEY (`iddocumento`, `categoria_idcategoria`, `comentario_idcomentario`, `comentario_comentario_idcomentario`),
  INDEX `fk_documento_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_documento_comentario1_idx` (`comentario_idcomentario` ASC, `comentario_comentario_idcomentario` ASC) VISIBLE,
  CONSTRAINT `fk_documento_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_comentario1`
    FOREIGN KEY (`comentario_idcomentario` , `comentario_comentario_idcomentario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`comentario` (`idcomentario` , `comentario_idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`publica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`publica` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`publica` (
  `Usuario_idUsuario` INT NOT NULL,
  `documento_iddocumento` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `publicacol` DATETIME NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `documento_iddocumento`),
  INDEX `fk_Usuario_has_documento_documento1_idx` (`documento_iddocumento` ASC) VISIBLE,
  INDEX `fk_Usuario_has_documento_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_documento_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_documento_documento1`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`descarga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`descarga` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`descarga` (
  `Usuario_idUsuario` INT NOT NULL,
  `documento_iddocumento` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `documento_iddocumento`),
  INDEX `fk_Usuario_has_documento_documento2_idx` (`documento_iddocumento` ASC) VISIBLE,
  INDEX `fk_Usuario_has_documento_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_documento_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_documento_documento2`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`visualiza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`visualiza` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`visualiza` (
  `Usuario_idUsuario` INT NOT NULL,
  `documento_iddocumento` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `documento_iddocumento`),
  INDEX `fk_Usuario_has_documento_documento3_idx` (`documento_iddocumento` ASC) VISIBLE,
  INDEX `fk_Usuario_has_documento_Usuario2_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_documento_Usuario2`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_documento_documento3`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_ALMCNAMIENTO`.`valora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_ALMCNAMIENTO`.`valora` ;

CREATE TABLE IF NOT EXISTS `proyecto_ALMCNAMIENTO`.`valora` (
  `Usuario_idUsuario` INT NOT NULL,
  `documento_iddocumento` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estrellas` ENUM("1-5") NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `documento_iddocumento`),
  INDEX `fk_Usuario_has_documento_documento4_idx` (`documento_iddocumento` ASC) VISIBLE,
  INDEX `fk_Usuario_has_documento_Usuario3_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_documento_Usuario3`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_documento_documento4`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `proyecto_ALMCNAMIENTO`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
